### ISSUE TITLE
Include AWS CodeStar/CloudFormation support

### ISSUE THREAD

**Issue by ChadMoran** [irvinlim/es2017-lambda-boilerplate#16]
It would be great if the boilerplate included template.yml and buildspec.yml to integrate with downstream dependencies like CodePipeline/CodeDeploy.

**Comment by irvinlim** [comment]
Hi Chad, I think that's a great suggestion! However, I don't have any prior experience working with CloudFormation or CodeStar.

In case you haven't already found out, Travis CI is already set up to deploy directly to AWS Lambda using the JavaScript AWS SDK (see [deploy.js](https://github.com/irvinlim/es2017-lambda-boilerplate/blob/master/bin/deploy.js)).

Nevertheless, I tried out CodePipeline with CloudFormation (following [this tutorial](http://docs.aws.amazon.com/lambda/latest/dg/build-pipeline.html)) and came up with #17. Since I'm not very familiar with different workflows when using CloudFormation, could I get you to review the PR?

My concern is that this configuration is specific only for CodePipeline - could I kindly get some input regarding how to set this up correctly?
