### ISSUE TITLE
Unexpected token import

### ISSUE THREAD

**Issue by VincentMolinie** [irvinlim/es2017-lambda-boilerplate#19]
When I tried your boilerplate I get:

```JSON
{
  "errorMessage": "Unexpected token import",
  "errorType": "SyntaxError",
  "stackTrace": [
    "Object.runInThisContext (vm.js:97:10)",
    "Module._compile (module.js:542:28)",
    "Object.Module._extensions..js (module.js:579:10)",
    "Module.load (module.js:487:32)",
    "tryModuleLoad (module.js:446:12)",
    "Function.Module._load (module.js:438:3)",
    "Module.require (module.js:497:17)",
    "require (internal/module.js:20:19)"
  ]
}
```

What is wrong ?

**Comment by irvinlim** [comment]
How are you running the code? Are you running it locally like this?

```sh
node src/index.js
```

A Lambda function isn't really meant to be run on your own local machine like this, since it's not a standalone application.

What I would recommend your workflow to be like is to do test-driven development (TDD), that is, write test cases as you are (or in fact, before) writing your function code. Then, run the tests using `npm run build`.

If you really want to just run the Lambda function on its own, you can use [`babel-node`](https://babeljs.io/docs/usage/cli/#babel-node) instead of `node` to run your code, but you also need to be calling the function from another file as well... Alternatively you can use `npm run build` to transpile down to ES5 before using `node` to call it.

**Comment by VincentMolinie** [comment]
My bad I was not up to date, it works with last version

**Comment by irvinlim** [comment]
No problem, did you mean latest version of the boilerplate, or Node?

**Comment by VincentMolinie** [comment]
Of the boilerplate ;)

**Comment by irvinlim** [comment]
Cool, thanks! :)
