### ISSUE TITLE
babel configuration

### ISSUE THREAD

**Issue by philippefuentes** [irvinlim/es2017-lambda-boilerplate#31]
Hi there,
I'm sorry I'm quite new to nodejs and other tools,
tried to run "npm run  build" then realised I had not installed babel
After installing babel globally, I realised I needed to install:

env preset
and other babel plugins refered in .babelrc.
```
         "add-header-comment",
        "transform-es2015-modules-commonjs",
        "transform-es2017-object-entries",
        "transform-object-rest-spread",
        "transform-es2015-destructuring",
        "array-includes"
```

what would be the right way to install all this component ? (--save-dev ? something else ?)

Thanks you for your help in advance

**Comment by irvinlim** [comment]
Hi, since there is a package.json file you can just do `npm install` in the root directory after cloning the repo. It should install all the relevant packages for you.

The plugins defined in `.babelrc` actually requires the packages to be installed via NPM (or Yarn) first, which is why Babel is complaining that it can't find the plugins.

Hope this helps!

**Comment by irvinlim** [comment]
If your `NODE_ENV` environment variable is set to `production` then it might not install the devDependecies. In that case, you should use `--save-dev`.

**Comment by philippefuentes** [comment]
Of course, sorry about that :)
Everything is fine now, thanks a lot !

**Comment by irvinlim** [comment]
Glad you fixed it! You can give this repository a star if it has been useful 😁

**Comment by philippefuentes** [comment]
first thing I did :)
